# SPDX-License-Identifier: MIT
# Copyright Siemens AG, 2025. Part of the SW360 Portal Project.
#
# Make sure the generated files are linted.

name: Generate Templates and Lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      - name: Generate template files
        run: |
          poetry run generate-groups DEPT DEPT2

  lint:
    runs-on: ubuntu-latest
    needs: generate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint the code
        run: |
          poetry run flake8 .
